### ISSUE TITLE
PostGIS operators

### ISSUE THREAD

**Issue by teohhanhui** [jsor/doctrine-postgis#15]
`&&`, `~` etc.

These can only be implemented as DQL functions, is that right?

**Comment by jsor** [comment]
These operators must be implemented in Doctrine itself as there is no way (AFAIK) to add new operators. As an alternative, you could implement a DQL function which handles these operators, like:

```
WHERE postgis_operator(geometry1, '&&', geometry2) = true
```

But this isn't really an improvement as you could also use:

```
WHERE ST_Overlaps(geometry1, geometry2) = true
```

**Comment by EvanCarroll** [comment]
I'm not sure you can just use `ST_Overlaps` because [the operator defines the gist access methods in PostGIS](https://github.com/postgis/postgis/blob/380583da73227ca1a52da0e0b3413b92ae69af9d/postgis/postgis.sql.in#L556). So while you'd get the same result using `ST_Overlaps`, it may be slow as horse poop.
