### ISSUE TITLE
Can't extend properly PostGISType

### ISSUE THREAD

**Issue by alexsegura** [jsor/doctrine-postgis#36]
Hello, 

I struggled when extending `GeographyType`, and then trying to execute migrations or schema diff.

I created a [`GeoJSONType`](https://github.com/coopcycle/coopcycle-web/commit/d4175e1ae2604178f15aa8a9982213845b7084b0#diff-8e75647cc0c89b3073abbc32a8c1cba8) to be able to manipulate GeoJSON arrays directly.
It extends `GeographyType`, and calls some PostGIS functions to make the conversion. 

With `bin/console doctrine:migrations:diff` or `bin/console doctrine:schema:update` I was always getting the following error

```
The type of a spatial column cannot be changed 
(Requested changing type from "geography" to "geojson" for column "polygon" in table "zone")
```

There were some problems in my first implementation, but even after activating comment hints & properly mapping my new type I as still getting the error. 

After a few hours debugging I found the problem. 

[`DBALSchemaEventSubscriber` does not care about the comments, it only reads the raw table definition](https://github.com/jsor/doctrine-postgis/blob/413baff3025ab0c6a7fff4397de099bc8464eb7c/src/Event/DBALSchemaEventSubscriber.php#L283).

Actually, my custom type creates a `geography` column in database, and `$tableColumn['type']` contains the actual type which is stored in database, not the custom one. 

To fix it I [extended DBALSchemaEventSubscriber](https://github.com/coopcycle/coopcycle-web/commit/861e85c34fd0b8c83524cac1eb698b34dde9f377).

I think this is definitely a bug.

**Comment by jsor** [comment]
I don't think it's a bug, just a use case i didn't thought about (but definitely an interesting one).

First, you can't easily change geometry/geography columns to another type because that always requires converting the stored values. That must be done by hand outside of the doctrine layer and that's the reason it throws an exception.

In this case, the column type isn't changed, so that needs to be addressed and i will look into that.

Another approach would be, to replace the geometry/geography types with types which convert to objects representing the geometries. I recently posted an example here: https://github.com/jsor/doctrine-postgis/issues/34#issuecomment-348698503

The example uses [geo-io/geometry](https://github.com/geo-io/geometry) for representing the geometries. The objects itself could be converted from/to GeoJSON with [geo-io/geojson](geo-io/geojson).

That's definitely a more sophisticated setup and you might also be aware of performance implications when working with really large geometry objects.

**Comment by jsor** [comment]
I'm closing this for now as i have no immediate interest and time to fix/implement this. If anyone feels like picking this up, i'm open for PR's.

**Comment by KouloukLeGrand** [comment]
@alexsegura thank you so much, you saved my day almost four years later!
