### ISSUE TITLE
Use with Laravel

### ISSUE THREAD

**Issue by BirdyUK** [jsor/doctrine-postgis#42]
Sorry to open an issue, im new to postgis so was hoping to find a wrapper that is easier to use than remembering all the SQL behind the postgis querys. Is it possible to use this with laravel by simply using composer to require the package, I noticed you mention symphony but nothing regarding laravel + other frameworks.

**Comment by jsor** [comment]
This package is specifically for [Doctrine](https://github.com/doctrine), not Symfony or Laravel. I only included some guidelines for Symfony because it was often asked in issues.

It could be used in Laravel only if you use Doctrine instead of Eloquent. You may have a look at [laravel-postgis](https://github.com/njbarrett/laravel-postgis) if you need PostGIS support for Eloquent.
